trigger:
  - main

pool:
  vmImage: "ubuntu-latest"

steps:
  - task: AzureCLI@2
    inputs:
      azureSubscription: "LogicAppviaBicep"
      scriptType: "bash"
      scriptLocation: "inlineScript"
      inlineScript: |
        az deployment group create \
          --resource-group Casestudy_ASBtoSQL \
          --template-file main.bicep \
          --parameters logicAppName=LogicApp_bicepdeploy
